# This is a basic workflow to help you get started with Actions

name: Scrape addresses on ref:ISTAT base

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
  workflow_dispatch:
  schedule:
    - cron: '5 11 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cheduled:
    runs-on: ubuntu-latest
    steps:
    - name: check out this repo
      uses: actions/checkout@v2
    - name: Get the data and analyze
      run: |
         chmod +x ./addr_stats_UD.sh
         ./addr_stats_UD.sh
      shell: bash
    - name: Commit and push if changed
      run: |-
         git config user.name "Automated"
         git config user.email "actions@users.noreply.github.com"
         git add -A
         timestamp=$(date -u)
         git commit -m "Latest data: ${timestamp}" || exit 0
         git push
