# This is a basic workflow to help you get started with Actions

name: Scrape hiking relations modified in last 24h

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
  workflow_dispatch:
  schedule:
    - cron: '22 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

# argument $1 is 3600000000 + areacode:
# 39152	Sicilia
# 40095	Puglia
# 40137	Basilicata
# 40218	Campania
# 40784	Lazio
# 41256	Molise
# 41977	Toscana
# 42004	Umbria
# 42611	Emilia-Romagna
# 43648	Veneto
# 44874	Piemonte
# 44879	Lombardia
# 45155	Valle d'Aosta/Vallée d'Aoste
# 45757	Trentino-Alto Adige/Südtirol
# 53060	Marche
# 53937	Abruzzo
# 179296	Friuli Venezia Giulia
# 301482	Liguria
# 1783980	Calabria
# 3792877	Auvergne-Rhône-Alpes
# 7361997	Sardegna

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: check out this repo
      uses: actions/checkout@v2
    - name: Get the data and analyze
      run: |
         chmod +x ./CAI_mods.sh
         chmod +x ./build-index.sh
         ./CAI_mods.sh fri && ./CAI_mods.sh ven && ./CAI_mods.sh emr && ./CAI_mods.sh lom && ./CAI_mods.sh pie && ./CAI_mods.sh lig && ./build-index.sh
      shell: bash
    - name: Commit and push if changed
      run: |-
         git config user.name "Automated"
         git config user.email "actions@users.noreply.github.com"
         git add -A
         timestamp=$(date -u)
         git commit -m "Latest data: ${timestamp}" || exit 0
         git push
